name: simple-terraform
description: Shortcuts for generating pipeline steps using terraform in docker for a simple workflows.
author: https://github.com/gantry-ml
requirements: ["bash", "docker"]
configuration:
  properties:
    path:
      type: string
    group:
      type: string
    queue:
      type: string
    docker-image:
      type: string
    docker-version:
      type: string
    terraform-version:
      type: string
    terraform-entrypoint-required:
      type: boolean
    terraform-module:
      type: string
    init:
      type: boolean
    validate:
      type: boolean
    plan:
      type: boolean
    apply:
      type: boolean
    destroy:
      type: boolean
    block:
      type: boolean
    wait:
      type: boolean
    validate_args:
      type: string
    plan_args:
      type: string
    init-args:
      type: string
    apply-args:
      type: string
    destroy-args:
      type: string
    propagate-aws-auth-tokens:
      type: boolean
    propagate-environment:
      type: boolean
    propagate-uid-gid:
      type: boolean
    suppress-steps:
      type: boolean
    debug:
      type: boolean
    assume-role:
      type: string
    tag:
      type: string
    environment:
      type: array
    volumes:
      type: array
    volumes:
      type: array
  required:
    - path
    - terraform-module
  additionalProperties: true
