#!/usr/bin/env bash
set -euo pipefail

PLUGIN_DEBUG="${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_DEBUG:-false}"
GROUP="${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_GROUP:-}"
TF_VALIDATE="${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_VALIDATE:-true}"
TF_INIT="${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_INIT:-true}"
TF_PLAN="${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_PLAN:-true}"
TF_APPLY="${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_APPLY:-false}"
TF_DESTROY="${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_DESTROY:-false}"
BLOCK="${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_BLOCK:-false}"
WAIT="${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_WAIT:-true}"
TF_INIT_ARGS="${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_INIT_ARGS:-}"
TF_VALIDATE_ARGS="${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_VALIDATE_ARGS:-}"
TF_PLAN_ARGS="${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_PLAN_ARGS:-}"
TF_APPLY_ARGS="${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_APPLY_ARGS:-}"
TF_DESTROY_ARGS="${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_DESTROY_ARGS:-}"
PROPAGATE_AWS_AUTH_TOKENS="${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_PROPAGATE_AWS_CREDENTIALS:-true}"
PROPAGATE_ENVIRONMENT="${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_PROPAGATE_ENVIRONMENT:-true}"
SUPPRESS_STEPS="${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_SUPPRESS_STEPS:-false}"
TAG="${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_TAG:-}"
TAGDASH=$([ -n "$TAG" ] && echo "-${TAG}" || echo "")
TAGBRACKET=$([ -n "$TAG" ] && echo "[$TAG]" || echo "")
TF_VERSION="${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_TERRAFORM_VERSION:-latest}"
DOCKER_IMAGE="${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_DOCKER_IMAGE:-hashicorp/terraform}"
TF_ENTRYPOINT_REQUIRED="${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_TERRAFORM_ENTRYPOINT_REQUIRED:-false}"
DOCKER_VERSION="${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_DOCKER_VERSION:-latest}"
DOCKER_PLUGIN_VERSION=$([ "$DOCKER_VERSION" = "latest" ] && echo "" || echo "#v${DOCKER_VERSION}")
TOP_INDENT=$([ "$SUPPRESS_STEPS" ] && echo "  " || echo "")
INDENT=$([ "$GROUP" ] && echo "${TOP_INDENT}    " || echo "${TOP_INDENT}")
PLAN_FILE="plan.tfplan"

WAIT_STEP=$'\n'$([ "$WAIT" = "true" ] && echo $'\n'"${INDENT}- wait" || echo "")$'\n\n'
BLOCK_STEP=$'\n'$([ "$BLOCK" != "false" ] && echo $'\n'"${INDENT}- block: \"Confirm apply ${TAGBRACKET}"\" || echo "")$'\n\n'
OUT="$([ "$SUPPRESS_STEPS" ] && echo "" || echo "steps:"$'\n'])"

BK_UID="$(id -u)"


get_artifact_block() {
  local command="${1}"
  local path="${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_PATH:-}"
  if [[ "${path}" == */ ]]; then
    path="${path%/}"
  fi
  case $command in 
    init)
      echo "${INDENT}  - artifacts:"
      echo "${INDENT}      compressed: terraform${TAGDASH}.tgz"
      echo "${INDENT}      upload: [ \"${path}/.terraform\", \"${path}/.terraform.lock.hcl\" ]"
      ;;
    validate)
      echo "${INDENT}  - artifacts:"
      echo "${INDENT}      compressed: terraform"${TAGDASH}".tgz"
      echo "${INDENT}      download: [ \"${path}/.terraform\", \"${path}/.terraform.lock.hcl\" ]"
      ;;
    plan)
      echo "${INDENT}  - artifacts:"
      echo "${INDENT}      compressed: terraform"${TAGDASH}".tgz"
      echo "${INDENT}      download: [ \"${path}/.terraform\", \"${path}/.terraform.lock.hcl\" ]"
      echo "${INDENT}  artifact_paths:"
      echo "${INDENT}    - \"${path}/plan"${TAGDASH}".tfplan\""
      ;;
    apply)
      echo "${INDENT}  - artifacts:"
      echo "${INDENT}      compressed: terraform"${TAGDASH}".tgz"
      echo "${INDENT}      download: [ \"${path}/.terraform\", \"${path}/.terraform.lock.hcl\" ]"
      echo "${INDENT}  - artifacts:"
      echo "${INDENT}      download: \"${path}/plan"${TAGDASH}".tfplan\""
      ;;
    esac
}


get_docker_command() {
  local command="${1}"
  local path="${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_PATH:-}"
  
  echo "${INDENT}      command:"
  if [[ "${TF_ENTRYPOINT_REQUIRED}" == "true" ]]; then
    echo "${INDENT}        - terraform"
  fi
  if [ -n "$path" ]; then
    echo "${INDENT}        - -chdir=${path}"
  fi
  case $command in 
    init)
      echo "${INDENT}        - init"
      if [ -n "${TF_INIT_ARGS}" ]; then
        echo "${INDENT}        - ${TF_INIT_ARGS}"
      fi
      echo "${INDENT}        - -input=false"
      ;;
    validate)
      echo "${INDENT}        - validate"
      if [ -n "${TF_VALIDATE_ARGS}" ]; then
        echo "${INDENT}        - ${TF_VALIDATE_ARGS}"
      fi
      
      ;;
    plan)
      echo "${INDENT}        - plan"
      if [ -n "${TF_PLAN_ARGS}" ]; then
        echo "${INDENT}        - ${TF_PLAN_ARGS}"
      fi
      echo "${INDENT}        - -input=false"
      echo "${INDENT}        - -out=plan"${TAGDASH}".tfplan"
      ;;
    apply)
      echo "${INDENT}        - apply"
      if [ -n "${TF_APPLY_ARGS}" ]; then
        echo "${INDENT}        - ${TF_APPLY_ARGS}"
      fi
      echo "${INDENT}        - -auto-approve"
      echo "${INDENT}        - -input=false"
      echo "${INDENT}        - plan"${TAGDASH}".tfplan"
      
      ;;
    destroy)
      echo "${INDENT}        - destroy"
      if [ -n "${TF_DESTROY_ARGS}" ]; then
        echo "${INDENT}        - ${TF_DESTROY_ARGS}"
      fi
      echo "${INDENT}        - -auto-approve"
      echo "${INDENT}        - -input=false"
      ;;
  esac
}

get_environment_block() {
  local command="${1}"

  local envs=()

  while IFS='=' read -r name _ ; do
    if [[ $name =~ ^(BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_ENVIRONMENT_[0-9]+) ]] ; then
      envs+=("${name}")
    fi
  done < <(env | sort)

  if [[ ${#envs[@]} -gt 0 ]]; then
    echo "${INDENT}      environment:"
    for env_var in "${envs[@]}"; do
      env_value=$(printenv "$env_var")
      echo "${INDENT}        - ${env_value}"
    done
  fi
}

get_volumes_block() {
  local command="${1}"

  local volumes=()

  while IFS='=' read -r name _ ; do
    if [[ $name =~ ^(BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_VOLUMES_[0-9]+) ]] ; then
      volumes+=("${name}")
    fi
  done < <(env | sort)

  if [[ ${#volumes[@]} -gt 0 ]]; then
    echo "${INDENT}      volumes:"
    for vol_var in "${volumes[@]}"; do
      vol_value=$(printenv "$vol_var")
      echo "${INDENT}        - ${vol_value}"
    done
  fi
}

get_user_block() {
  local command="${1}"

  local user="${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_USER:-}"

  if [ ! -z "${user}" ]; then
    echo "${INDENT}      user: \""${user}"\""
  fi
}


get_docker_block() {
  local COMMAND_BLOCK=$(get_docker_command "$1")
  local USER_BLOCK=$(get_user_block "$1")
  local ARTIFACT_BLOCK=$(get_artifact_block "$1")
  local ENVIRONMENT_BLOCK=$(get_environment_block "$1")
  local VOLUMES_BLOCK=$(get_volumes_block "$1")

  if [ -n "${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_ASSUME_ROLE:-}" ]; then
    local ASSUME_BLOCK=$(cat <<EOF
${INDENT}  - gantry-ml/aws-assume-role-in-current-account:
${INDENT}      role: "${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_ASSUME_ROLE:-}"
${INDENT}      duration: "1800"
EOF
    )

  fi

  if [ -n "${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_QUEUE:-}" ]; then
    local QUEUE_BLOCK=$(cat <<EOF
${INDENT}  agents:
${INDENT}    queue: ${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_QUEUE}
EOF
    )
  fi

cat <<EOF
${QUEUE_BLOCK:-}
${INDENT}  plugins:
${ASSUME_BLOCK:-}
${INDENT}  - docker${DOCKER_PLUGIN_VERSION}:
${INDENT}      image: "${DOCKER_IMAGE}:${TF_VERSION}"
${INDENT}      propagate-environment: ${PROPAGATE_ENVIRONMENT}
${INDENT}      propagate-aws-auth-tokens: ${PROPAGATE_AWS_AUTH_TOKENS}
${USER_BLOCK:-}
${ENVIRONMENT_BLOCK:-}
${COMMAND_BLOCK:-}
${VOLUMES_BLOCK:-}
${ARTIFACT_BLOCK:-}
EOF

}

get_concurrency_block() {
  local command="${1}"
  local terraform_module="${BUILDKITE_PLUGIN_SIMPLE_TERRAFORM_TERRAFORM_MODULE}"

  local concurrency=1
  local concurrency_group="${terraform_module}/${command}"
  local concurrency_block=$(cat <<EOF
${INDENT}  concurrency: ${concurrency}
${INDENT}  concurrency_group: "${concurrency_group}"
EOF
  )

  echo "${concurrency_block}"
}


if [ -n "$GROUP" ]; then
  OUT+='  - group: "'${GROUP}$'"\n'
  if [ "$SUPPRESS_STEPS" ]; then
    OUT+=$'    steps:\n'
  fi
fi

if [ "$TF_INIT" = "true" ]; then
  OUT+="${INDENT}- label: \":terraform: Init ${TAGBRACKET}\""
  OUT+=$'\n'
  OUT+=$(get_docker_block "init")
fi

if [ "$TF_VALIDATE" = "true" ]; then
  OUT+=$WAIT_STEP
  OUT+="${INDENT}- label: \":terraform: Validate ${TAGBRACKET}\""
  OUT+=$'\n'
  OUT+=$(get_docker_block "validate")
fi

if [ "$TF_PLAN" = "true" ]; then
  OUT+=$WAIT_STEP
  OUT+="${INDENT}- label: \":terraform: Plan ${TAGBRACKET}\""
  OUT+=$'\n'
  OUT+=$(get_concurrency_block "plan")
  OUT+=$'\n'
  OUT+=$(get_docker_block "plan")
fi

if [ "$TF_APPLY" = "true" ]; then
  OUT+=$WAIT_STEP
  if [ -n "$BLOCK" ]; then
    OUT+=$BLOCK_STEP
  fi
  OUT+="${INDENT}- label: \":terraform: Apply ${TAGBRACKET}\""
  OUT+=$'\n'
  OUT+=$(get_concurrency_block "apply")
  OUT+=$'\n'
  OUT+=$(get_docker_block "apply")
fi

if [ "$TF_DESTROY" = "true" ]; then
  OUT+=$WAIT_STEP
  if [ -n "$BLOCK" ]; then
    OUT+=$BLOCK_STEP
  fi
  OUT+="${INDENT}- label: \":terraform: Destroy ${TAGBRACKET}\""
  OUT+=$'\n'
  OUT+=$(get_concurrency_block "apply")
  OUT+=$'\n'
  OUT+=$(get_docker_block "apply")
fi

echo "$OUT" 

if [ "$PLUGIN_DEBUG" != "true" ]; then
  echo "# Uploading pipeline..."
  echo "$OUT" | buildkite-agent pipeline upload
fi
